app = "ferchoportafolio"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "10s"
    timeout  = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/"
