app = "ferchoportafolio"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"  # <-- Buildpacks de Python

[http_service]
  internal_port = 8080            # Buildpacks exponen $PORT=8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
